GLOBAL format_b:	BYTE
GLOBAL format_d:	BYTE
GLOBAL format_u:	BYTE
GLOBAL format_x:	BYTE
GLOBAL format_s:	BYTE
GLOBAL format_lb:	BYTE
GLOBAL format_ld:	BYTE
GLOBAL format_lu:	BYTE
GLOBAL format_lx:	BYTE
GLOBAL format_2d:	BYTE
GLOBAL format_3d:	BYTE
GLOBAL format_02X:	BYTE
GLOBAL format_04X:	BYTE
GLOBAL format_08X:	BYTE
GLOBAL format_08Xh:	BYTE
GLOBAL format_s_d:	BYTE
GLOBAL format_lbb:	BYTE
GLOBAL format_16X:	BYTE
GLOBAL format_8ld:	BYTE
GLOBAL format_010lu:	BYTE


